name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      env:
        TEST_ACCOUNT : ${{ secrets.TEST_ACCOUNT }}
        TEST_PASSWORD : ${{ secrets.TEST_PASSWORD }}
        TEST_CLIENT_ID : ${{ secrets.TEST_CLIENT_ID }}
        TEST_CLIENT_SECRET : ${{ secrets.TEST_CLIENT_SECRET }}
        TEST_REDIRECT_URL : ${{ secrets.TEST_REDIRECT_URL }}
        BOX_DEVELOPER_TOKEN : ${{ secrets.BOX_DEVELOPER_TOKEN }}
      run: |
        mvn -B package --file pom.xml
